### ISSUE TITLE
`next` server fails to launch

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-agent-js#109]
One of two errors may appear. This issue is easily recreated using a sample project and created along with the following commands:
```sh
$ npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
$ cd nextjs-blog
$ npx @appland/appmap install
$ npx appmap-agent-js -- node node_modules/.bin/next dev -p 3001
```

The errors are as follows:
```
$ npx appmap-agent-js -- node node_modules/.bin/next dev -p 3001
(node:95565) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95565) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
/Users/dustin/dev/tmp/next-test/nextjs-blog/node_modules/next/dist/bin/next:158
commands[command]().then((exec)=>exec(forwardedArgs)).then(()=>{
                                 ^

TypeError: exec is not a function
    at /Users/dustin/dev/tmp/next-test/nextjs-blog/node_modules/next/dist/bin/next:158:34
```

```
$ npx appmap-agent-js -- node node_modules/.bin/next dev -p 3001
/Users/dustin/dev/tmp/next-test/nextjs-blog/node_modules/@appland/appmap-agent-js/lib/node/abomination.js:38
      throw new Error(
      ^

Error: Unable to solve the file extension issue of ESM loader -- see: https://github.com/nodejs/node/issues/41465
    at Function.executeUserEntryPoint [as runMain] (/Users/dustin/dev/tmp/next-test/nextjs-blog/node_modules/@appland/appmap-agent-js/lib/node/abomination.js:38:13)
    at node:internal/main/run_main_module:17:47
```

**Comment by lachrist** [comment]
Hi @dustinbyrne thanks for the bug report. The second issue is probably due to you tempering with a bin file in the next npm module. Extension-less files cause problems -- cf: https://github.com/nodejs/node/issues/41465. So I rename them with an explicit `.cjs` extension. If the extension-less file and the `.cjs` file are not identical, I crash the agent instead of continuing with something inconsistent. We could discuss whether a simple warning would suffice. I'm looking at the root failure now.

**Comment by lachrist** [comment]
@dustinbyrne I got the agent to produce interesting appmaps but the viewer is not showing much. Should @dividedmind proceed with the reviewing?

To reproduce:

```sh
git clone https://github.com/land-of-apps/agent-js-sandbox.git
cd agent-js-sandbox
node nextjs/setup.mjs --agent-branch=nextjs-fix-clean
cd nextjs-blog
npx appmap-agent-js
```

<img width="1392" alt="Screenshot 2022-09-02 at 18 14 45" src="https://user-images.githubusercontent.com/5468597/188197389-38731b5b-e7ee-488b-8c0b-c9c6c2f046af.png">

[anonymous.appmap.json.zip](https://github.com/applandinc/appmap-agent-js/files/9479618/anonymous.appmap.json.zip)
