### ISSUE TITLE
Bug: WARNINGs are logged when logging level set to Error.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#32]
```‣ npx appmap-agent-js
APPMAP-WARNING command "git describe --abbrev=0 --tags" on cwd "/Users/ptrdvrk/work/github/js/bitmidi.com" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --abbrev=0" on cwd "/Users/ptrdvrk/work/github/js/bitmidi.com" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long --tags" on cwd "/Users/ptrdvrk/work/github/js/bitmidi.com" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long" on cwd "/Users/ptrdvrk/work/github/js/bitmidi.com" failed with 128 >> fatal: No names found, cannot describe anything.
```

**Comment by lachrist** [comment]
Hi Petr, there is a misunderstanding here :|.
I understood what the issue is and it is the expected behavior.
Could I ask you to double read my initial response?

**Comment by lachrist** [comment]
So I think this is feature request, not a bug

**Comment by ptrdvrk** [comment]
I see what you mean (logging from code that has not been configured by appmap.yml, yet), but it still does not feel right from the user's perspective. Not a high priority issue at this point. Perhaps the log level does not belong to the appmap.yml.

**Comment by lachrist** [comment]
I try to put everything in the configuration and it lead to some pretty clean design. I agree that it does not feel right. So I would rather split the process of loading the configuration rather than split the configuration data itself. This is indeed less urgent than the other issues.

**Comment by kgilpin** [comment]
Log level would be normally specified in the environment

**Comment by ptrdvrk** [comment]
LGTM,
```npx appmap-agent-js --log=error --recorder=remote -- main.app.js```
 now does the right thing

(note: `--log` to be replaced with `--log-level` and `--recorder` to become optional, soon)
