### ISSUE TITLE
Feat: appmap-agent-js provides basic usage help and version

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#34]
`npx appmap-agent-js --help` provides basic usage help.
`npx appmap-agent-js --version` prints out the version of the agent.

**Comment by lachrist** [comment]
Done in: https://github.com/applandinc/appmap-agent-js/commit/3bb79b22563bc27cdbaffb738021d12dae1930c8

**Comment by ptrdvrk** [comment]
1. help now prints out version
2. any reason why not `--help` and `--version` but `help` and `version`?

**Comment by lachrist** [comment]
It is easier to threat those as positional argument rather than named arguments.
The first argument after the node executable defines what it should do.
Other popular CLI are doing this as well -- eg:`git`.

**Comment by lachrist** [comment]
help now prints out version fixed in: https://github.com/applandinc/appmap-agent-js/commit/923fadcecc2190e0f204599d67d07651525b7958

**Comment by lachrist** [comment]
`--version` and `--help` form supported in 0bd7f74b1f1fd12e16ef89a2a062334606bd942e

**Comment by ptrdvrk** [comment]
@lachrist can we hide the "setup" command from the help? I understand it can be useful for advanced configuration eventually but at this moment, we want the users to use the CLI Install / getting started flow that does not mention the setup command.
Moving back to in progress until this comment is resolved.

**Comment by lachrist** [comment]
Done in 669fc754b8bd68e3820896d348b65f67a18ca210
