### ISSUE TITLE
Bug: "view source" of a function navigates to a wrong function in the source

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#35]
See this example: `createNonce#()` -> view source -> the correct source file is opened, but the cursor is positioned in the `serverStatic()` function above createNonce.

Project: bitmidi.com

AppMap attached.

![image](https://user-images.githubusercontent.com/42008542/138915369-b5b787ea-8a33-43fc-ab46-9da533a180a1.png)

[manual_no_db.appmap.json.txt](https://github.com/applandinc/appmap-agent-js/files/7419621/manual_no_db.appmap.json.txt)

**Comment by lachrist** [comment]
If you still have the project ready to run, could you check if it is still the case in 6.3.2?

**Comment by ptrdvrk** [comment]
Something's off, now I cannot start the app with the agent.

"@appland/appmap-agent-js": "^6.3.2",

[error.txt](https://github.com/applandinc/appmap-agent-js/files/7463735/error.txt)

**Comment by lachrist** [comment]
Ok there is two things here: the deprecated esm hook and the relative data url problem. I will try to solve this first thing in the morning, ty!

**Comment by lachrist** [comment]
I'm having a hard time to get bitmidi to run on my machine. Is this still an issue?

**Comment by lachrist** [comment]
Closing this in absence of complain. Feel free to re-open this.
