### ISSUE TITLE
Feat: Basic configuration and initial setup standardization

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#39]
- [x] Hide "trivial" advanced options from the initial configuration in appmap.yml - Laurent will check and complete this today (11/8)
  - ordering, default: causal
  - pruning, default: true
  - source, default: false //inlining source in AppMaps
  - "record-children-processes": true (not sure what the latest name of this option is)
- [x] Move operational configuration to command parameters - Laurent is going to work on this today 11/8
  - [x] `--log-level` , default: `info`
  - [x]  `--output-dir` , default: `tmp/appmap` 
    - [x] or `tmp/appmap/mocha` for the mocha recorder
  - ~[ ] `--appmap-config`, default: `appmap.yml`~
- [x] #45
  - [x] `app` -> `name`
  - [x] Review the configuration of included/excluded packages (take a look at python, for example)
    Example tha should work:
    ```yaml
    name: Test
    packages:
      - path: lib
      - path: models
      - path: frontent
    ```
- [x] Is the `--command` needed? Can we revert back to `npx appmap-agent-js -- node main.mjs argv0 argv1` ? 
  - This requires a bit more work, expansion of globs etc makes it more complicate than it looks like, we can update later 
- [x] Hooks configuration should be transparent and optional for the end user: all active by default without breaking the app if "hooked library" not present in project
  - Should be possible to fix by 11/9 EOD  
- [x] Simplify the "recorder" configuration
   - Multiple configurations in appmap.yml should not be needed for different recording methods. Instead, the recorder should work like other languages - automatically detect and record from tests, enable remote and programmatic recording in running apps, record entire processes optionally (runtime parameter/variable override)
   - Should by doable by tomorrow with a simple heuristics: if "mocha" in command, run mocha. Otherwise remote recording. Retain the parameter to override the heuristics and to utilize the process recorder.
- Move the selection/whitelisting of RR ports to runtime parameters starting the agent
  - [x] `--app-port`, default: inferred (white-listing of a specific app port, otherwise all ports are spied on)
  - [x] `--alt-remote-port`, default: 0

**Comment by lachrist** [comment]
I think I'm done with this for the time being.

The only thing that remains is: `--appmap-config` command line argument. For now this can only be set via environment variables: `APPMAP_CONFIGURATION_PATH`. Currently, each command line argument represent a configuration field. Adding `--appmap-config` would break that. Because I don't think changing the configuration path is going to be used that often, I would like to avoid implementing this feature for the time being.

**Comment by ptrdvrk** [comment]
Thank you Laurent! Makes sense, I'll move the `--appmap-config` parameter to a separate ticket.

**Comment by lachrist** [comment]
app-port and alt-remote-port supported in dab7d5b725d98e668226c5478c536d6b961b4b21
