### ISSUE TITLE
Rename existing properties in appmap.yml for consistency with other languages

### ISSUE THREAD

**Issue by lachrist** [applandinc/appmap-agent-js#45]

**Comment by lachrist** [comment]
The `app` configuration can be left blank and the application name will be retrieved from the package json will be used. It is just a matter of hiding these 'advanced' options.

**Comment by lachrist** [comment]
I misunderstood the problem. Here is the fix:

https://github.com/applandinc/appmap-agent-js/commit/f8b2c35da3e0fa47df45857f0def10513f3fb936

**Comment by ptrdvrk** [comment]
LGTM
