### ISSUE TITLE
Path matching criteria in appmap.yml are too strict

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#50]
The gist of this issue is, these two configurations should both whitelist functions in `server/app/routes/auth.js`, but only configuration 2) does. All other appmap agents use the "starts with" matching for paths/package names in both inclusion and exclusion rules, and `appmap-agent-js` needs to do the same.

1)
```
name: Chat
packages:
- path: server
```

2)
```
name: Chat
packages:
- path: server/app/routes
```

**Comment by lachrist** [comment]
Should be done in: cbf6b341946a742cadab680b804615f03003ed42
