### ISSUE TITLE
Class/function with an event not present in class map.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#51]
See this appmap (for https://github.com/dye784/Chat-App.git): 
[Test7.appmap.json.txt](https://github.com/applandinc/appmap-agent-js/files/7529787/Test7.appmap.json.txt)

arrow-35 and arrow-36 classes have corresponding function call events but are missing in the class map.

**Comment by lachrist** [comment]
I think I know what is going on. I assumed that if a function was not called, then none of its nested function could be called. This would be correct if the trace was complete but this might not always be the case. With remote recording for instance we can generate partial trace. I'm working on a fix.

**Comment by lachrist** [comment]
This should be fixed in: 696741e85e7b93c93618882697ee2de88ea6ca7c

**Comment by ptrdvrk** [comment]
LGTM.
