### ISSUE TITLE
Structure and naming of packages should be consistent with other languages

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#54]
IMO the package name of this code object should be `controllers/account.controller.js`, not just `account.controllers.js` for consistency with other languages.

https://app.land/scenarios/2c7da711-e57d-471c-9c3a-eaf8bf44fa03?state=%257B%2522currentView%2522%3A%2522viewComponent%2522%2C%2522selectedObject%2522%3A%2522package%3Acontrollers%2Faccount.controller.js%2522%257D

**Comment by lachrist** [comment]
Done in: f36b7310e71c1a0e7a03d1fc49d548410da71298
I added a configuration field so that we can easily toggle between the two options.
