### ISSUE TITLE
Warn: HTTP activity detected after closing both the request and the response

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#55]
Remote recording of some apps shows similar comments in the log:
```
POST /login 302 60020.566 ms - 56
GET /login 200 17.022 ms - 2418
GET /css/vendor/bootstrap/css/bootstrap.min.css 304 0.747 ms - -
GET /css/flat-ui.css 304 1.369 ms - -
GET /css/style.css 304 1.102 ms - -
GET /js/vendor/jquery.min.js 304 2.646 ms - -
GET /js/flat-ui.min.js 304 0.577 ms - -
GET /fonts/lato/lato-regular.woff 304 0.720 ms - -
GET /fonts/glyphicons/flat-ui-icons-regular.woff 304 0.534 ms - -
GET /img/icons/svg/clipboard.svg 404 16.678 ms - 4277
APPMAP-WARNING HTTP activity detected after closing both the request and the response.
```

@lachrist: The agent assumed that an http cycle was done yet it detected some lingering activity afterward. I can imagine the following reasons for it:

1. The method for detecting the end of the cycle is wrong. This means that we are missing some information in the bundle of events associated to the cycle. I've tried different method and the current seems to work the best (least amount of warnings).
2. The node engine recycled the request/response. This is more serious because we might miss entire cycles. I'm not aware that node would do that but who knows...

I think this is one of these cases where if nothing seems to be wrong then we can just leave this issue at rest. Yet we should know that is a potential vulnerability in the agent.

**Comment by lachrist** [comment]
Let's leave this issue open to see if better http request/response cycle is warranted.

**Comment by lachrist** [comment]
http hook revamped in https://github.com/applandinc/appmap-agent-js/pull/110
